config/routes.rb
require 'resque/server'
Rails.application.routes.draw do

  authenticate :user do
    mount Resque::Server => "/resque"
  end

  # specifically for devfest
  get '/devfest', to: redirect('/gdg-new-delhi/events/devfest-18')

  resources :kommunities, only: [:new, :create, :edit, :update], param: :kommunity

  scope ':kommunity' do

    get '/',
        to: 'kommunities#show',
        as: :kommunity_show

    resources :events, only: [:index, :new, :create, :edit, :update, :show] do
      member do

        post 'assign-data-form',
             to: 'event_data_form_entity_groups#assign_data_form_entity',
             as: :assign_data_form

        post 'create-form-set',
             to: 'event_data_form_entity_groups#create',
             as: :create_form_set

        delete 'destroy-form-set',
               to: 'event_data_form_entity_groups#destroy',
               as: :destroy_form_set


        get 'update-registration-status-counter',
            to: 'event_data_form_entity_groups#update_registration_status_counter',
            as: :update_registration_status_counter


        delete 'remove-data-form-entity',
               to: 'data_form_entities_events#remove_data_form_entity',
               as: :remove_data_form_entity

        post 'form/update-visibility',
            to: 'data_form_entities_events#update_visibility',
            as: :update_form_visibility


        put 'update-event-status',
            to: 'events#update_event_status',
            as: :update_event_status

        put 'update-header-image',
            to: 'events#update_header_image',
            as: :update_header_image


        get 'all-responses',
            to: 'events#all_responses',
            as: :all_responses


        get 'resources',
            to: 'events#public_resources',
            as: :public_resources


        get 'session-discussions',
            to: 'speaker_resources#session_discussions',
            as: :session_discussion


        resources :event_location_tracks, path: 'event-location-tracks', only: [:create, :destroy], shallow: true do
          resources :track_slots, path: 'track-slots', only: [:create, :destroy], shallow: true
        end


        resources :comments, only: [:create, :destroy], shallow: true do
          resources :comments, only: [:create, :destroy]
        end


        resources :speaker_resources, path: 'speaker-resources', only: [:new, :create, :update]


      end

      resources :locations, only: [:create, :destroy]

      resources :event_updates, only: [:create, :destroy]

    end

    resources :data_forms, path: 'data-forms', only: [:new, :create, :edit, :update]


    resources :event_entry_passes, path: 'event-entry-passes', only: [:create] do
      member do
        patch :toggle_attendance, as: 'toggle-attendance'
        patch :toggle_uninvited, as: 'toggle-uninvited'
      end

      collection do
        get :auto_attendance, as: 'auto-attendance'
        patch :mark_attendance, as: 'mark-attendance'
      end
    end




    # INDIVIDUAL URLS

    # data_form_entity_responses_controller
    get 'fill-form',
        to: 'data_form_entity_responses#fill_form',
        as: :fill_form_response


    post 'response',
         to: 'data_form_entity_responses#submit_form',
         as: :submit_form_response

    put 'form-responses/update-registration_status',
        to: 'data_form_entity_response_groups#update_registration_status',
        as: :update_response_registration_status



    get 'update-rsvp',
        to: 'data_form_entity_response_groups#update_rsvp',
        as: :update_rsvp



    # data_form_entities_controller
    get 'form-responses',
        to: 'data_form_entities#form_responses',
        as: :form_responses

    get 'form-responses-data',
        to: 'data_form_entities#form_responses_data',
        as: :form_responses_data


    # data_form_entity_responses_controller
    put 'user-event-locations/update-selected-location',
        to: 'user_event_locations#update_selected_location',
        as: :update_user_event_selected_location



    #event_communications_mailer
    resources :event_communication_mailers, path: "event-communication-mailers" do
      collection do
        get :data_form_entity_response_group_rsvp_email, path: "user-rsvp-email"
        post :send_data_form_entity_response_group_rsvp_email, path: "send-user-rsvp-email"
        get :event_data_form_entity_group_rsvp_email, path: "event-users-rsvp-email"
        post :send_event_data_form_entity_group_rsvp_email, path: "send-event-users-rsvp-email"
        get :data_form_entity_response_group_entry_pass_email, path: "user-entry-pass-email"
        post :send_data_form_entity_response_group_entry_pass_email, path: "send-user-entry-pass-email"
        get :event_data_form_entity_group_entry_pass_email, path: "event-users-entry-pass-email"
        post :send_event_data_form_entity_group_entry_pass_email, path: "send-event-users-entry-pass-email"

        get :feedback_email, path: "feedback-email"
        post :send_feedback_email, path: "send-feedback-email"

        get :registration_email, path: "registration-email"
        post :send_registration_email, path: "send-registration-email"
      end
    end

    resources :discussions, only: [:create]

  end


  resources :user_messages, only: [:create]



  match '*all', to: proc { [204, {}, ['']] }, via: :options

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }



  root "home#home"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :kommunity
  belongs_to :user
  belongs_to :event_status

  has_many :event_data_form_entity_groups
  has_many :event_entry_passes
  has_many :event_location_tracks
  has_many :event_locations
  has_many :user_event_locations, :through => :event_locations
  has_many :locations, through: :event_locations
  has_many :comments, as: :commentable
  has_many :event_updates

  has_one_attached :header_image



  after_save :create_log, if: :will_save_change_to_event_status_id?

  before_validation :init


  # scopes
  default_scope { includes(:event_status, :kommunity) }
  scope :with_locations, -> {includes(:locations)}
  scope :with_comments, -> {includes(:comments)}

  ##

  def init
    self.event_status  ||= EventStatus.find_by_name(NameValues::EventStatusType::DRAFT)
  end


  def create_log(current_user = nil)
    current_user = CurrentAccess.user.blank? ? current_user : CurrentAccess.user
    if current_user

      EventStatusLog.create(
                        event: self,
                        user: current_user,
                        event_status: self.event_status
      )

    else
      return "Event Status Change Log Not Created"

    end
  end


  def self.upcoming(kommunity_id: nil)

    if(kommunity_id.blank?)
      return Event.joins(:event_status, :kommunity).where(
                      "event_statuses.name = ? and start_time >= ?",
                      NameValues::EventStatusType::ANNOUNCED, Time.now.beginning_of_day
      ).order("start_time asc")
    else
      return Event.joins(:event_status).where(
          "event_statuses.name = ? and kommunity_id = ? and start_time >= ?",
          NameValues::EventStatusType::ANNOUNCED, kommunity_id, Time.now.beginning_of_day
      ).order("start_time asc")
    end

  end

  def self.recent_past(kommunity_id: nil, count: 5)
    if kommunity_id.blank?
      return Event.joins(:event_status, :kommunity).where(
          "event_statuses.name = ? and start_time <= ?",
          NameValues::EventStatusType::COMPLETED, Time.now.end_of_day
      ).order("start_time desc").limit(count)
    else
      return Event.joins(:event_status).where(
          "event_statuses.name = ? and kommunity_id = ? and start_time <= ?",
          NameValues::EventStatusType::COMPLETED, kommunity_id, Time.now.end_of_day
      ).order("start_time desc").limit(count)
    end
  end


  def status? (event_status_names)
    return event_status_names.include? self.event_status.name
  end

  # change this function to permitted forms
  # send if a user has already filled a form along with the list of permitted forms
  def open_forms

    open_forms = []
    self.event_data_form_entity_groups.each do |edfeg|
      edfeg.data_form_entities.each do |dfe|
        # show only visible forms
        if (dfe.can_fill_event_form(CurrentAccess.user) && !dfe.open_but_invisible?)
          open_forms << dfe
        end
      end
    end

    open_forms

  end


  def start_time
    self[:start_time].blank? ? Time.now : self[:start_time].in_time_zone(self.timezone)
  end


  def end_time
    self[:end_time].blank? ? Time.now : self[:end_time].in_time_zone(self.timezone)
  end



  # list of all data form entity response groups which have been confirmed
  def confirmed_speaker_registrations

    DataFormEntityResponseGroup.joins(:user, :registration_status, event_data_form_entity_group: [:registration_type, :event]).where(
        "events.id = ? and registration_types.name = ? and registration_statuses.name = ?",
        self.id, NameValues::RegistrationsType::SPEAKER, NameValues::RegistrationStatusType::CONFIRMED
    )

  end


  def get_available_speakers
    DataFormEntityResponseGroup.includes(:user).joins(:registration_status, event_data_form_entity_group: [:event, :registration_type]).where('events.id = ? and registration_types.name = ? and registration_statuses.name = ?', self.id, NameValues::RegistrationsType::SPEAKER, NameValues::RegistrationStatusType::CONFIRMED)
  end



  # this method should go to the resque_worker
  def send_feedback_emails(form_id, subject, message, force = false)

    self.event_entry_passes.includes(:event).where(attendance: true).each do |eep|

      if (force || eep.fixed_email_sent?(NameValues::FixedEmailType::FEEDBACK)[0] == false)
        Resque.enqueue(FeedbackMailerWorker, eep.id, form_id, subject, message)
      end

    end


  end

  # sort alphabetically by the name of the speakers
  def public_resources
    return SpeakerResource.joins(data_form_entity_response_group: [:user, {event_data_form_entity_group: :event}]).where('events.id = ?', self.id).order('lower(users.name)')
  end


  # TODO add photos link
  # def get_photos
  #   album_id = 'AF1QipNohy1dAsIrw9zq8KBr6_3dODJwIf38v5Bwj47hRivWtUGKkp4bI1EGi-_5H3C41w'
  #   response = RestClient.post(
  #       'https://photoslibrary.googleapis.com/v1/mediaItems:search',
  #       {albumId: album_id},
  #       headers={
  #           'Authorization': "Bearer #{ENV["GDG_GOOGLE_CLIENT_ID"]}"
  #       }
  #   )
  # end



end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  # before_action :set_kommunity
  before_action :authenticate_user!, except: [:show, :public_resources]
  before_action :set_event, only: [:show, :edit, :update, :assign_data_form, :remove_data_form_entity, :update_event_status, :update_header_image, :all_responses, :public_resources]
  before_action :access_allowed?



  def index
    @events = Event.includes(:kommunity, :event_data_form_entity_groups).joins(:kommunity).upcoming(kommunity_id: @kommunity.id)
    @event_location_track = EventLocationTrack.new
    @track_slot = TrackSlot.new
  end

  def show

    @event_statuses = EventStatus.all
    @event_location_track = EventLocationTrack.new
    @track_slot = TrackSlot.new
    @location = Location.new
    @new_comment = Comment.new
    @new_event_update = EventUpdate.new

  end


  def new

    @event = Event.new

  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
    @event.timezone = ActiveSupport::TimeZone.all.collect{|z| z.tzinfo.name if z.utc_offset == event_params[:start_time].utc_offset}.compact![0]
    if @event.save
      redirect_to action: :show, id: @event
    else
      render :new
    end
  end


  def edit


  end

  def update
    @event.update_attributes(event_params)
    @event.timezone = ActiveSupport::TimeZone.all.collect{|z| z.tzinfo.name if z.utc_offset == event_params[:start_time].utc_offset}.compact![0]
    if @event.save
      redirect_to action: :show, kommunity: @event.kommunity, id: @event
    else
      render :edit
    end

  end



  def update_event_status
    @event.event_status = EventStatus.find(params[:event_status])
    @event.save

    @event_statuses = EventStatus.all
  end


  def update_header_image
    # remove the existing header_image
    @event.header_image.attached? ? @event.header_image.purge : false
    @event.header_image.attach(params[:header_image])

  end

  # currently using this for all attendees only
  def all_responses
    @all_response_groups = DataFormEntityResponseGroup.joins(:registration_status, event_data_form_entity_group: {event: :event_entry_passes}).where('event_data_form_entity_groups.event_id = ? and registration_statuses.name = ?', @event.id, NameValues::RegistrationStatusType::CONFIRMED).joins(:event_data_form_entity_group).includes(:user, event_data_form_entity_group: :event).uniq

    @entry_passes = EventEntryPass.where(event_id: @event.id)

  end


  def public_resources
    
    @speaker_resources = SpeakerResource.joins(data_form_entity_response_group: {event_data_form_entity_group: :event}).where('events.id = ?', @event.id)
  end


  private

  def set_event
    @event = Event.includes(:user, event_data_form_entity_groups: {data_form_entities: :data_form}).find_by(slug: params[:id], kommunity_id: @kommunity.id)
    RolePermission.event = @event
  end

  def event_params
    params[:event][:start_time] = params[:event][:start_time].to_datetime
    params[:event][:end_time] = params[:event][:end_time].to_datetime
    params.require(:event).permit(:name, :kommunity_id, :start_time, :end_time, :description, :seats)
  end



end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_assigned_form_list_item.html.erb
<li class="data-form-entity-<%= dfe.id %>">
  <%= dfe.data_form.name %>

  &nbsp

  <% if dfe.data_form_entity_responses.length == 0 %>
  <%= link_to 'Remove', remove_data_form_entity_event_path(id: @event, entity_id: dfe), remote: true, method: :delete %>

  <% end %>


  <%= link_to 'Fill', fill_form_response_path(event_id: @event, data_form_entity_id: dfe) %>

  <%= link_to 'View Responses', form_responses_path(event_id: @event, data_form_entity_id: dfe) %>
</li>

app/views/events/_available_resources.html.erb
<section id="event-resources-<%= event.id %>" class="bg-white p-2">
  <h3>Slides and Details from Talks</h3>

  <ul class="list-group d-flex p-0 flex-row flex-wrap">
    <% event.public_resources.each do |pr| %>
    <li class="card list-group-item m-2 col-sm-2 col-1 shadow-sm  text-center">
      <%= link_to session_discussion_event_path(speaker_resource: pr.id) do %>
      <p class="m-0">
        <%= pr.data_form_entity_response_group.user.name %>
      </p>
      <% end %>
    </li>
    <% end %>

  </ul>

</section>

app/views/events/_confirmed_speakers.html.erb
<div id="confirmed-event-speakers-<%= event.id %>" class="shortlisted-speakers-container">
<h3>The Speakers</h3>
  <ul class="list-group d-flex flex-row flex-wrap justify-content-around p-3 bg-white shortlisted-speakers-list">
    <% event.confirmed_speaker_registrations.shuffle.each do |evs| %>
      <li class="list-group-item shadow-sm mb-3">
        <%= render 'speaker_display_card', user: evs.user %>
      </li>

    <% end %>

  </ul>

</div>

app/views/events/_event_comments.html.erb
<section class="event-comments bg-white p-3" id="event-comments-<%= event.id %>">
  <h4>Comments</h4>


  <div>
    <ul class="list-group list-group-flush" id="event-comments-list-<%= event.id %>">
      <% event.comments.order('created_at').each do |comment| %>
      <%= render 'comments/comment', comment: comment %>
      <% end %>
    </ul>

  </div>

  <% if user_signed_in? %>
  <%= form_for new_comment, html: {class: 'row event-comment-form', id: "event-comments-form-#{event.id}"}, remote: true do |f| %>

  <div class="col-10">
    <%= f.text_area :body, class: 'form-control', placeholder: 'Say Something...!', rows: 1, onkeydown: 'textAreaRowIncrementor(event, this);', required: true %>
  </div>
  <div class="col-2">
    <%= button_tag type: 'submit', class: "btn btn-info p-2 comment-submit-button" do %>
    <i class='fas fa-arrow-alt-circle-right fa-2x text-white'></i>
    <% end %>
  </div>


  <% end %>
  <% else %>


  <%= link_to "Sign In / Sign Up To Comment", user_google_oauth2_omniauth_authorize_path %>




  <% end %>




</section>

app/views/events/_event_show_header.html.erb
<div id="event-header-container-<%= event.id %>">
  <div>
    <% if allowed_view?(:events, :edit) %>
    <h5><%= link_to "Edit",  edit_event_path(id: event), class: "badge badge-primary" %></h5>
    <% end %>

  </div>
  <div class="event-header d-flex align-items-center p-3 my-3 text-white-50 bg-purple rounded ", id="event-header-background" style= '<%= event.header_image.attached? ? "background: url(#{url_for(event.header_image)});" : ""  %>'>
  <!--<img class="mr-3" src="../../assets/brand/bootstrap-outline.svg" alt="" width="48" height="48">-->
    <div class="lh-100">
      <div class="<%= event.header_image.attached? ? 'hidden-item' : '' %>">
        <% if event.kommunity.logo_image.attached? %>
        <p class="text-center mb-0">
          <img alt="<%= event.kommunity.name %> Logo" src="<%= url_for(event.kommunity.logo_image) %>" width="50" class="mr-2">
        </p>


        <% end %>
        <p class="mb-0 text-center">
          <span><%= event.kommunity.name %></span>

        </p>
        <h1 class="mb-0 text-white lh-100"> <%= event.name %></h1>
        <div class="badge badge-light mt-3">
          <%= render 'events/event_time_display', event: event %>
        </div>
        <div class="mt-2 mb-0 text-white d-flex flex-sm-column flex-md-row ">

          <% event.locations.each_with_index do |elc, index| %>
          <p class="m-2 ">
            <i class="fas fa-map-marker-alt mr-1"></i>
            <strong><%= elc.name %></strong>, <span class="text-light"><%= elc.address %></span>
          </p>

          <% end %>
        </div>

      </div>

      <% if allowed_view?(:events, :update_header_image) %>
      <div>
        <%= form_with url: update_header_image_event_path(id: event), id: 'event-header-image-form', method: :put do |f|%>
        <div class="form-group">
          <%= f.label :header_image, 'Choose Header', for: 'event-header-image', class: 'custom-file-label' %>
          <%= f.file_field :header_image, class: 'custom-file-input', onChange: 'showImage(this, "event-header-background", "background");', id: 'event-header-image', onchange: 'Rails.fire(this.form, "submit")', accept: "image/*" %>

        </div>
        <%= f.submit 'Upload', class: 'btn btn-outline-info' %>
        <% end %>
      </div>
      <% end %>


    </div>
  </div>

</div>

app/views/events/_event_time_display.html.erb
<div id="event-timing">

  <% if event.start_time.to_date != event.end_time.to_date %>
  <span>
                  <span>
                    <%= event.start_time.strftime("%A") %>, <%= event.start_time.strftime("%d-%b-%Y") %></span> <span class=""> <%= event.start_time.strftime('%I:%M %p') %></span> -

                  <span><%= event.end_time.strftime("%A") %>, <%= event.end_time.strftime("%d-%b-%Y") %></span> <span class=""> <%= event.end_time.strftime('%I:%M %p') %></span>

                </span>
  <% else %>
  <span>
    <span><%= event.start_time.strftime("%A") %>, <%= event.start_time.strftime("%d-%b-%Y") %></span>
    <span class=""> <%= event.start_time.strftime('%I:%M %p') %> To <%= event.end_time.strftime('%I:%M %p') %></span>

  </span>
  <% end %>

</div>

app/views/events/_locations_tracks_slots.html.erb
<div class="event-location-track-slots-widget" id="event-tracks-creator-<%= event.id %>">
  <div class=" p-3">

    <h3>Agenda <% if event.event_location_tracks.empty? %><small>(Coming Soon)</small><% end %></h3>
    <div class="event-location-tracks-grid">
      <% if !event.event_location_tracks.empty? || (user_signed_in? && current_user.role?(:organizer, event.kommunity_id)) %>
      <div class="row">

        <div class="col-md-2">
          <p class="mb-0">
            <small class="text-muted">Venue</small>
          </p>
          <div class="nav bg-white p-3  flex-md-column flex-sm-row flex-sm-nowrap justify-content-md-center nav-pills" id="v-pills-event-locations-tab" role="tablist" aria-orientation="vertical">
            <% event.event_locations.each_with_index do |elc, index| %>
            <a class="nav-link <%= index == 0 ? 'active' : '' %>" id="v-pills-elc-<%= elc.id %>-tab" data-toggle="pill" href="#v-pills-elc-<%= elc.id %>" role="tab" aria-controls="v-pills-elc-<%= elc.id %>" aria-selected="<%= index == 0 ? true : false %>">
              <%= elc.location.name %>
            </a>
            <% end %>
            <% if allowed_view?(:locations, :create) %>
            <a class="nav-link btn text-left" id="add-location-button"  data-toggle="modal" data-target="
            #new-event-location-modal">
              <i class="fas fa-plus-circle fa-1x text-success"></i> Add Location
            </a>
            <% end %>
          </div>
        </div>

        <div class="col-md-10 p-0">
          <div class="tab-content" id="v-pills-tabContent">
            <% event.event_locations.each_with_index do |elc, index| %>

            <%= render 'events/event_location_track', index: index, elc: elc, event: event %>

            <% end %>
          </div>
        </div>
      </div>
      <% end %>
    </div>

  </div>

</div>

app/views/events/index.html.erb
<% content_for :page_title do %>
<%= @kommunity.name %> | Events
<% end %>
<h4 class="bg-info text-center text-white p-2"><%= @kommunity.name %></h4>

<% if allowed_view?(:events, :create) %>
<div class="card mt-3 p-3 d-flex">
  <%=  link_to new_event_path do %>
    <span><i class="fas fa-plus-circle fa-1x text-success"></i> Create Event</span>
  <% end %>
</div>
<% end %>

<div>

  <div class="row justify-content-center">

    <div class="col-md-9 ">

      <div class="row d-flex flex-md-row flex-sm-column flex-wrap justify-content-center">
        <% @events.each do |event| %>

        <div class="col-md-4 m-2 p-0">
          <%= render 'events/event_mini_card', event: event %>
        </div>


        <% end %>

      </div>

    </div>

  </div>




</div>

app/views/events/new.html.erb
<% content_for :page_title do %>
Add Your Community
<% end %>

<h3 class="text-center">New Event</h3>


<%= render 'form' %>

app/views/events/show.html.erb
<% content_for :page_title do %>
  <%= @kommunity.name %> | <%= @event.name %>
<% end %>


<section id="events-show">

    <div>

      <!--<a class="twitter-timeline" href="https://twitter.com/gdg_nd?ref_src=twsrc%5Etfw">Tweets by gdg_nd</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>-->
    </div>

    <div>

      <%= render 'events/event_show_header', event: @event %>

      <!--<p class="badge badge-info badge">Seats: <%= @event.seats %></p>-->

      <div></div>

      <div class="mt-3 mb-3">
        <% if allowed_view?(:events, :update_event_status) %>
        <%= render 'event_status_select', event: @event, event_statuses: @event_statuses %>
        <% end %>
      </div>
      <div class="d-flex flex-md-row flex-sm-column flex-wrap justify-content-md-start justify-content-sm-center">
        <% @event.open_forms.each do |dfe| %>


        <%= link_to fill_form_response_path(kommunity: @event.kommunity, data_form_entity_id: dfe), target: '_blank', class: "btn form-link shadow p-2 m-2 " do %>

        <i class="fas fa-arrow-alt-circle-right"></i> <strong><%= dfe.entity.name.titlecase %></strong>
        <% end %>

        <% end %>
      </div>


    </div>




  <% if allowed_view?(:data_form_entities, :form_responses) %>
  <div class="d-flex row .flex-wrap ">
    <div class=" p-3 m-2 col-md-3">
      <%= form_with url: create_form_set_event_path(id: @event), scope: :event_data_form_entity_group, method: 'post', remote: true do |f| %>
      <h5>Create Form Set</h5>
      <small>Something like registration form, feedback form, etc..</small>
      <div class="form-group">
        <div class="field">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="field">
          <%= f.label :registration_type %>
          <%= f.select :registration_type_id, options_for_select(RegistrationType.all.collect{|m| [m.name, m.id]}), {}, class: 'form-control' %>

        </div>
        <%= f.submit "Create Form Set", class: 'btn' %>

      </div>

      <% end %>
    </div>
    <div class=" p-2 mt-3">


      <ul class="list-group" id="form-set-list">
        <li class="list-group-item">
          <%= link_to 'All Confirmations', all_responses_event_path, class: 'btn btn-primary' %>
        </li>
        <%= render partial: 'event_data_form_entity_groups/form_set', collection: @event.event_data_form_entity_groups, as: :edfeg, locals: {event: @event} %>

      </ul>



    </div>


  </div>

  <% end %>

  <% if @event.status? ([NameValues::EventStatusType::COMPLETED]) %>
  <div>
    <%= render 'events/available_resources', event: @event %>
  </div>
  <% end %>


  <%= render 'events/locations_tracks_slots', event: @event, track_slot: @track_slot, event_location_track: @event_location_track %>

  <% if !@event.confirmed_speaker_registrations.empty? %>
  <div>
    <%= render 'confirmed_speakers', event: @event %>
  </div>
  <% end %>


  <div class="d-flex flex-md-row flex-sm-column flex-wrap justify-content-md-around mt-5">
    <div class="col-md-6 col-sm-12">
      <%= render 'events/event_description', event: @event, new_event_update: @new_event_update %>
    </div>

    <div class="m-1 col-md-5 col-sm-12 ">

      <%= render 'events/event_comments', event: @event, new_comment: @new_comment %>

    </div>
  </div>














  <% if allowed_view?(:locations, :create) %>
  <div class="modal fade" id="new-event-location-modal" tabindex="-1" role="dialog" aria-labelledby="new-event-location-modal-title" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="new-event-location-modal-title">Add <%= @event.name %> Location</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">


          <div class="mt-3 mb-3 d-flex">


            <div class="card-body">
              <%= form_for Location.new, url: event_locations_path(event_id: @event), remote: true do |f| %>
              <div class="form-group">
                <%= f.label :name %>
                <%= f.text_field :name, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :address %>
                <%= f.text_field :address, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :map_link %>
                <%= f.text_field :map_link, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.submit 'Add Location', class: 'btn btn-outline-info' %>
              </div>
              <% end %>
            </div>


          </div>



        </div>
      </div>
    </div>
  </div>
  <% end %>


  <% if allowed_view?(:event_location_tracks, :create) %>
  <div class="modal fade" id="new-event-location-track-modal" tabindex="-1" role="dialog" aria-labelledby="new-event-location-modal-title" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="new-event-location-track-modal-title">Add <%= @event.name %> Track For a Location</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">


          <div class="mt-3 mb-3 d-flex">


            <div class="card-body">
              <%= render 'event_location_tracks/form', event: @event, event_location_tack: EventLocationTrack.new %>
            </div>


          </div>



        </div>
      </div>
    </div>
  </div>
  <% end %>

  <% content_for :page_scripts do %>
  <script>

  </script>
  <% end %>
</section>

app/views/events/update_event_status.js.erb
{

    $('#event-status-select').replaceWith($("<%= escape_javascript render 'event_status_select', event: @event, event_statuses: @event_statuses %>"));


    let notification = new Noty({
        text: 'Status Updated!',
        theme: 'relax',
        type: 'success',
        timeout: 1500
    }).show();
}